# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finefile',
            name='fine_file',
            field=models.FileField(upload_to=''),
        ),
    ]
