# Generated by Django 2.1 on 2018-08-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_auto_20180805_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
