# Generated by Django 2.1.4 on 2018-12-19 18:38

from django.db import migrations, models
import solverREST.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=solverREST.models.imageFile)),
            ],
        ),
    ]
